### ISSUE TITLE
(Unix/bluesteel) - Flag 4 is readable by any user.

### ISSUE THREAD

**Issue by spenceradolph** [mintyjazz/sep-ctf#13]
Flag4.txt in initial testing of this room appeared readable without having to switch to the derek user.
This may or may not be intentional, but my interpretation of the walkthrough makes me think users are supposed to find flag3 to get credentials for the derek user.

From the walkthrough....
```
14) This file contains another set of credentials - switch to this user on the challenge box and investigate their home for the final flag.
```

The line in question on the docker file can be found here...
https://github.com/mintyjazz/sep-ctf/blob/8eaa99c9f84c234662e372243ed16a5690f96f99/Unix/bluesteel/Resources/ubuntu1/Dockerfile#L42

@sloth333

**Comment by sloth333** [comment]
Thanks for the heads up, you are correct - the intent was for the file only to be viewable by the derek user.  I remember this file only being viewable by root previously, the referenced chmod command fixed that but I see left it too open.  I modified the dockerfile in question and created a new pull to remedy the issue.
